apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone-api
spec:
  template:
    spec:
      containers:
        - name: keystone-api
          volumeMounts:
            - mountPath: /etc/keystone/fernet-keys/
              name: fernet-keys-fixed
            - mountPath: /etc/keystone/credential-keys/
              name: credential-keys-fixed
