---
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
                - worker

loglevel: info
rabbitmq:
  url: http://rabbitmq:15672
  user: guest
  password: guest
  # If existingUserSecret is set then user is ignored
  existingUserSecret: rabbitmq-default-user
  existingUserSecretKey: username
  # If existingPasswordSecret is set then password is ignored
  existingPasswordSecret: rabbitmq-default-user
  existingPasswordSecretKey: password

prometheus:
  monitor:
    enabled: true
    namespace:
      - openstack
      - monitoring
