---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: swift
  namespace: openstack
spec:
  tags:
    - management  # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
    - policymaker
  rabbitmqClusterReference:
    name: rabbitmq  # rabbitmqCluster must exist in the same namespace as this resource
    namespace: openstack
  importCredentialsSecret:
    name: swift-rabbitmq-password
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: swift-vhost
  namespace: openstack
spec:
  name: "swift"  # vhost name; required and cannot be updated
  defaultQueueType: quorum  # default queue type for this vhost; require RabbitMQ version 3.11.12 or above
  rabbitmqClusterReference:
    name: rabbitmq  # rabbitmqCluster must exist in the same namespace as this resource
    namespace: openstack
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: swift-queue
  namespace: openstack
spec:
  name: swift-qq  # name of the queue
  vhost: "swift"  # default to '/' if not provided
  type: quorum  # without providing a queue type, rabbitmq creates a classic queue
  autoDelete: false
  durable: true  # setting 'durable' to false means this queue won't survive a server restart
  rabbitmqClusterReference:
    name: rabbitmq  # rabbitmqCluster must exist in the same namespace as this resource
    namespace: openstack
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: swift-permission
  namespace: openstack
spec:
  vhost: "swift"  # name of a vhost
  userReference:
    name: "swift"  # name of a user.rabbitmq.com in the same namespace; must specify either spec.userReference or spec.user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq  # rabbitmqCluster must exist in the same namespace as this resource
    namespace: openstack
