# I don't believe the OpenStack helm Neutron chart offers the ability to use
# optional volume mounts, and this secret may not exist on installations not
# using Kube-OVN's "control plane" TLS
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: neutron-ovn-metadata-agent-default
spec:
  template:
    spec:
      volumes:
        - name: ovn-tls
          secret:
            optional: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neutron-server
spec:
  template:
    spec:
      volumes:
        - name: ovn-tls
          secret:
            optional: true
