# The resources contained in this file (ovn-backup.yaml) write OVN NB and SB
# snapshots to a persistent volume, assuming you installed OVN with kubespray,
# since it assumes resources exist as seen in the
# genestack/submodules/kubespray/roles/network_plugin/kube-ovn/templates
# directory, assuming you have checked out the genestack submodules.
# (For instance, it uses the `ovn` service account as seen in
# genestack/submodules/kubespray/roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovndb-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: general
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ovn-snapshot-cron
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        spec:
          serviceAccount: "ovn"
          serviceAccountName: "ovn"
          restartPolicy: "Never"
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: ovndb-backup
          - name: backup-script
            configMap:
              name: ovn-backup-script
              defaultMode: 0744
          containers:
          - name: ovn-central-backup
            envFrom:
              - configMapRef:
                  name: ovn-backup-config
              - secretRef:
                  name: ovn-backup-swift-tempauth-account
            command: ["/backup-script/ovn-backup.sh"]
            image: docker.io/kubeovn/kube-ovn:v1.11.5
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: backup
              mountPath: "/backup"
            - name: backup-script
              mountPath: /backup-script
