apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo
resources:
  - ../base

patches:
  - target:
      kind: StatefulSet
      name: memcached-memcached
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
