---

- name: Remove legacy cinder staging files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/cinder/cinder.conf.stage"
    - "/etc/cinder/{{ cinder_worker_name }}-cinder.conf.stage"
