---

- name: Set enabled backend fact
  ansible.builtin.set_fact:
    cinder_backend: |
      {% set rendered_backend = {} %}
      {% for backend in cinder_backend_name.split(',') %}
      {%   set default_backend = (_kubernetes_cinder_etc_secret.resources[0].data['backends.conf'] | b64decode | community.general.from_ini)[backend] %}
      {%   set _ = rendered_backend.__setitem__(backend, default_backend) %}
      {% endfor %}
      {{ rendered_backend }}

- name: "Create the cinder-volume-{{ cinder_worker_name }} backend configuration"
  ansible.builtin.copy:
    content: "{{ cinder_backend | community.general.to_ini }}"
    dest: "/etc/cinder/{{ cinder_worker_name }}-backends.conf"
    owner: root
    group: cinder
    mode: "0640"
  notify:
    - "Restart cinder-volume-backend systemd services"

- name: "Create the cinder-volume-{{ cinder_worker_name }} worker configuration override"
  ansible.builtin.copy:
    content: |
      [DEFAULT]
      host = cinder-volume-{{ cinder_worker_name }}-worker
      enabled_backends = {{ cinder_backend_name }}
    dest: "/etc/cinder/{{ cinder_worker_name }}-cinder.conf"
    owner: root
    group: cinder
    mode: "0640"
  notify:
    - "Restart cinder-volume-backend systemd services"

- name: "Create the cinder-volume-{{ cinder_worker_name }} systemd service units"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - src: "../templates/cinder-volume-storage.service"
      dest: "/etc/systemd/system/cinder-volume-{{ cinder_worker_name }}.service"
    - src: "../templates/sudoers"
      dest: /etc/sudoers.d/cinder-volume
      mode: "0440"
  notify:
    - "Restart cinder-volume-backend systemd services"
