additionalPrometheusRulesMap:
  openstack-services-rabbitmq:
    groups:
      - name: rabbitmq-alerts
        rules:
          - alert: NovaQueueTotalToLarge
            expr: rabbitmq_queue_messages{vhost="nova"} > 25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Nova vhost has too many messages"
              description: "Nova vhost in RabbitMQ has too many messages. Check consumers."

          - alert: GlanceQueueTotalToLarge
            expr: rabbitmq_queue_messages{vhost="glance"} > 25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Glance vhost has too many messages"
              description: "Glance vhost in RabbitMQ has too many messages. Check consumers."

          - alert: NeutronQueueTotalToLarge
            expr: rabbitmq_queue_messages{vhost="neutron"} > 25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Neutron vhost has too many messages"
              description: "Neutron vhost in RabbitMQ has too many messages. Check consumers."

          - alert: KeystoneQueueTotalToLarge
            expr: rabbitmq_queue_messages{vhost="keystone"} > 25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Keystone vhost has too many messages"
              description: "Keystone vhost in RabbitMQ has too many messages. Check consumers."

          - alert: CinderQueueTotalToLarge
            expr: rabbitmq_queue_messages{vhost="cinder"} > 25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Cinder vhost has too many messages"
              description: "Cinder vhost in RabbitMQ has too many messages. Check consumers."

          - alert: MagnumQueueTotalToLarge
            expr: rabbitmq_queue_messages{vhost="magnum"} > 25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Magnum vhost has too many messages"
              description: "Magnum vhost in RabbitMQ has too many messages. Check consumers."

          - alert: OctaviaQueueTotalToLarge
            expr: rabbitmq_queue_messages{vhost="octavia"} > 25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Octavia vhost has too many messages"
              description: "Octavia vhost in RabbitMQ has too many messages. Check consumers."

          - alert: BarbicanQueueTotalToLarge
            expr: rabbitmq_queue_messages{vhost="barbican"} > 25
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Barbican vhost has too many messages"
              description: "Barbican vhost in RabbitMQ has too many messages. Check consumers."
