apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: memcached
  namespace: openstack
spec:
  $patch: replace
  maxReplicas: 9
  minReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: memcached
