---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

resources:
  - all.yaml
  - hpa.yaml

patches:
  - target:
      kind: StatefulSet
      name: memcached-memcached
    path: memcached-statefulset-extra-env-vars-patch.yaml

  - target:
      kind: ConfigMap
      name: memcached-memcached-bin
    path: memcached-bin-configmap-patch.yaml
