---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

resources:
  - all.yaml

patches:
  - target:
      kind: StatefulSet
      name: memcached-memcached
    path: memcached-statefulset-extra-env-vars-patch.yaml

  - target:
      kind: ConfigMap
      name: memcached-memcached-bin
    path: memcached-bin-configmap-patch.yaml

  - path: memcached-service-session-affinity-config-patch.yaml
    target:
      kind: Service
      name: memcached

  - path: memcached-statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: memcached-memcached
