sortOptions:
  order: fifo
resources:
  - ../base/envoy-gateway-namespace.yaml
  - ../base/envoy-internal-gateway-issuer.yaml
  - ../base/envoy-custom-proxy-config.yaml
  - ../base/envoy-gatewayclass.yaml
  - ../base/all.yaml
