---
- name: Remove first 164 characters from /root/.ssh/authorized_keys
  hosts: all
  become: yes
  vars:
    ansible_user: ubuntu
  tasks:
    - name: Remove the first 164 characters from the authorized_keys file
      shell: "tail -c +165 /root/.ssh/authorized_keys > /root/.ssh/authorized_keys.tmp && mv /root/.ssh/authorized_keys.tmp /root/.ssh/authorized_keys"
      args:
        executable: /bin/bash
      become: yes

    - name: Ensure correct permissions on the authorized_keys file
      file:
        path: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0600'

    - name: Copy ssh key to nodes
      ansible.builtin.copy:
        src: ./key
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: '0600'
