---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manila-share
  namespace: openstack
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - share
              topologyKey: kubernetes.io/hostname
