---
apiVersion: v1
kind: Service
metadata:
  name: ironic-prometheus-exporter
  labels:
    app.kubernetes.io/name: ironic-prometheus-exporter
spec:
  selector:
    application: ironic
    component: conductor
  ports:
    - name: metrics
      port: 9608
      targetPort: metrics
      protocol: TCP
