sortOptions:
  order: fifo
resources:
  - ../base

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: ceilometer-notification
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
