images:
  - name: image-kubernetes-entrypoint-init
    newName: ghcr.io/rackerlabs/genestack-images/kubernetes-entrypoint
    newTag: latest
  - name: image-heat-conf-init
    newName: ghcr.io/rackerlabs/genestack-images/heat
    newTag: 2024.1-latest
  - name: image-cinder-volume-netapp-init
    newName: ghcr.io/rackerlabs/genestack/cinder-volume-rxt
    newTag: 2024.1-ubuntu_jammy
  - name: image-cinder-volume-netapp
    newName: ghcr.io/rackerlabs/genestack/cinder-volume-rxt
    newTag: 2024.1-ubuntu_jammy

sortOptions:
  order: fifo
resources:
  - configmap-etc.yaml
  - deploy-volume-netapp.yaml
  - hpa-cinder-volume-netapp.yaml
