images:
  - name: image-kubernetes-entrypoint-init
    newName: quay.io/airshipit/kubernetes-entrypoint
    newTag: v1.0.0
  - name: image-heat-conf-init
    newName: docker.io/openstackhelm/heat
    newTag: 2024.1-ubuntu_jammy
  - name: image-cinder-volume-netapp-init
    newName: docker.io/openstackhelm/cinder
    newTag: 2024.1-ubuntu_jammy
  - name: image-cinder-volume-netapp
    newName: docker.io/openstackhelm/cinder
    newTag: 2024.1-ubuntu_jammy

resources:
  - configmap-etc.yaml
  - deploy-volume-netapp.yaml
  - hpa-cinder-volume-netapp.yaml
