---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: custom-keystone-gateway-route
  namespace: openstack
spec:
  parentRefs:
    - name: flex-gateway
      sectionName: keystone-https
      namespace: envoy-gateway
  hostnames:
    - "keystone.your.domain.tld"
  rules:
    - backendRefs:
        - name: keystone-api
          port: 5000
      sessionPersistence:
        sessionName: KeystoneSession
        type: Cookie
        absoluteTimeout: 300s
        cookieConfig:
          lifetimeType: Permanent
