---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: custom-barbican-gateway-route
  namespace: openstack
spec:
  hostnames:
    - barbican.your.domain.tld
  parentRefs:
    - name: flex-gateway
      namespace: envoy-gateway
      sectionName: barbican-https
  rules:
    - backendRefs:
        - name: barbican-api
          port: 9311
