---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: zaqar
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "zaqar"
    meta.helm.sh/release-namespace: "openstack"
spec:
  mariaDbRef:
    name: mariadb-cluster
  characterSet: utf8
  collate: utf8_general_ci
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: zaqar
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "zaqar"
    meta.helm.sh/release-namespace: "openstack"
spec:
  mariaDbRef:
    name: mariadb-cluster
  passwordSecretKeyRef:
    name: zaqar-db-password
    key: password
  maxUserConnections: 0
  host: "%"
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: zaqar-grant
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "zaqar"
    meta.helm.sh/release-namespace: "openstack"
spec:
  mariaDbRef:
    name: mariadb-cluster
  privileges:
    - "ALL"
  database: "zaqar"
  table: "*"
  username: zaqar
  grantOption: true
  host: "%"
  retryInterval: 5s
