---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: designate
  namespace: openstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  # If you want the database to be created with a different name than the resource name
  # name: data-custom
  mariaDbRef:
    name: mariadb-cluster
  characterSet: utf8
  collate: utf8_general_ci
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: designate
  namespace: openstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: mariadb-cluster
  passwordSecretKeyRef:
    name: designate-db-password
    key: password
  # This field is immutable and defaults to 10, 0 means unlimited.
  maxUserConnections: 0
  host: "%"
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: designate-grant
  namespace: openstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  mariaDbRef:
    name: mariadb-cluster
  privileges:
    - "ALL"
  database: "designate"
  table: "*"
  username: designate
  grantOption: true
  host: "%"
  retryInterval: 5s
