---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudkitty-api
  namespace: openstack
spec:
  maxReplicas: 9
  minReplicas: 2
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudkitty-api
