---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: masakari-hostmonitor
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: masakari-hostmonitor
subjects:
  - kind: ServiceAccount
    name: masakari-host-monitor
    namespace: openstack
roleRef:
  kind: ClusterRole
  name: masakari-hostmonitor
  apiGroup: rbac.authorization.k8s.io
