apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: placement-api
  namespace: openstack
spec:
  maxReplicas: 9
  minReplicas: 3
  metrics:
    - resource:
        name: memory
        target:
          averageValue: 500Mi
          type: Value
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: placement-api
