# Set the custom_host variable to the desired hostname for Grafana
# This is used to set the domain and root_url in the grafana.ini file
# and the value of the custom_host variable must be a valid domain.
custom_host: grafana.example.com

persistence:
  type: pvc
  enabled: true
  storageClassName: general
  accessModes:
    - ReadWriteMany

nodeSelector:
  openstack-control-plane: enabled

ingress:
  enabled: false

image:
  tag: "10.3.3"

grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ .Values.custom_host }}"  # Ref: custom_host variable above
    root_url: "https://{{ .Values.custom_host }}"  # Ref: custom_host variable above
  database:
    type: mysql
    host: mariadb-cluster.grafana.svc:3306
    user: $__file{/etc/secrets/grafana-db/username}
    password:  $__file{/etc/secrets/grafana-db/password}
    name: grafana

datasources:
  datasources.yaml:
    apiversion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
      isdefault: true
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.{{ $.Release.Namespace }}.svc.cluster.local:80
      editable: false

alerting:
  rules.yaml:
    groups:
        - orgId: 1
          name: loki 1 min eval
          folder: rules
          interval: 1m
          rules:
            - uid: ba943125-33ca-4e4e-85f8-13359a8e4d65
              title: OVN claim storm
              condition: B
              data:
                - refId: A
                  queryType: instant
                  relativeTimeRange:
                    from: 60
                    to: 0
                  datasourceUid: P8E80F9AEF21F6940
                  model:
                    editorMode: builder
                    expr: rate({app="ovs"} |= `binding|INFO|cr-lrp` [1m])
                    intervalMs: 60000
                    maxDataPoints: 43200
                    queryType: instant
                    refId: A
                - refId: B
                  relativeTimeRange:
                    from: 60
                    to: 0
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 1
                                - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params: []
                          reducer:
                            params: []
                            type: avg
                          type: query
                    datasource:
                        name: Expression
                        type: __expr__
                        uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: B
                    type: threshold
              noDataState: OK
              execErrState: Error
              for: 0s
              notifications:
                - uid: prom-alertmanager-notification
              annotations:
                description: >-
                  Checks app=ovs (ovs-ovn) pod logs for lines with string
                  'binding|INFO|cr-lrp'
                summary: >-
                  This alerts on rapid port claims for cr-lrp ports on OVN
                  gateway nodes, which overloads the OVN south database and
                  interferes with the function of the affected ports.
              labels: {}
              isPaused: false
  contactpoints.yaml:
    secret:
      apiVersion: 1
      contactPoints:
        - orgId: 1
          name: prom-alertmanager-notification
          receivers:
            - uid: ed4884f5-6e37-4a11-af5e-63f83bd26e94
              type: prometheus-alertmanager
              settings:
                url: http://alertmanager-operated.prometheus.svc.cluster.local:9093
              disableResolveMessage: false
  notification_policies.yaml:
    apiVersion: 1
    orgId: 1
    policies:
      - receiver: prom-alertmanager-notification
        default: true
        group_wait: 1s
        group_interval: 1s
        repeat_interval: 1s

plugins:
  - camptocamp-prometheus-alertmanager-datasource

extraSecretMounts:
  - name: grafana-db-secret-mount
    secretName: grafana-db
    defaultMode: 0440
    mountPath: /etc/secrets/grafana-db
    readOnly: true
