#!/bin/bash
# Install baseline packages and tools for Debian.
set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

apt-get update -qq
apt-get install -y -qq \
    apt-transport-https \
    ca-certificates \
    curl \
    default-mysql-client \
    gnupg \
    iputils-ping \
    lsb-release \
    net-tools \
    sudo \
    telnet \
    traceroute \
    chrony >/dev/null
