apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-cluster
  namespace: openstack
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: false
  username: mariadb
  database: mariadb
  image: image-mariadb

  storage:
    size: 10Gi
    storageClassName: general
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: general

  replicas: 3
  podSecurityContext:
    runAsUser: 0

  replication:
    enabled: true

  service:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/address-pool: primary
  connection:
    secretName: mariadb-cluster-conn
    secretTemplate:
      key: dsn

  primaryService:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/address-pool: primary
  primaryConnection:
    secretName: mariadb-cluster-conn-primary
    secretTemplate:
      key: dsn

  secondaryService:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/address-pool: primary
  secondaryConnection:
    secretName: mariadb-cluster-conn-secondary
    secretTemplate:
      key: dsn

  updateStrategy:
    type: RollingUpdate

  myCnf: |
    [mariadb]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=ROW
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
    max_connections=10240
    open_files_limit=10240
    max-connect-errors=1000000
    innodb_rollback_on_timeout=1
    performance_schema=ON
    innodb_log_buffer_size=33554432
    innodb_flush_log_at_trx_commit=1
    ignore-db-dirs=lost+found
    skip-name-resolve
    innodb_buffer_pool_size=4G
    innodb_doublewrite=0
    innodb_file_per_table=1
    innodb_flush_method=O_DIRECT
    innodb_io_capacity=500
    innodb_log_file_size=1G
    innodb_old_blocks_time=1000
    innodb_read_io_threads=8
    innodb_write_io_threads=8

    wait_timeout=3600
    interactive_timeout=3600
    net_read_timeout=360
    net_write_timeout=360

    sync_binlog=1
    thread_cache_size=16
    table_open_cache=2048
    table_definition_cache=1024

  metrics:
    enabled: false
