---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-cluster
  namespace: openstack
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - worker
  # NOTE: (brew) uncomment below when we update to a newer mariadb crd
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - mariadb-cluster
          topologyKey: kubernetes.io/hostname
  connection:
    secretName: mariadb-cluster-conn
    secretTemplate:
      key: dsn
  database: mariadb
  image: docker-registry1.mariadb.com/library/mariadb:11.4.3
  metrics:
    enabled: false
  myCnf: |
    [mariadb]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=ROW
    binlog_expire_logs_seconds=172800
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
    max_connections=10240
    open_files_limit=10240
    max-connect-errors=1000000
    innodb_rollback_on_timeout=1
    performance_schema=ON
    innodb_log_buffer_size=33554432
    innodb_flush_log_at_trx_commit=1
    ignore_db_dirs=lost+found
    skip-name-resolve
    innodb_buffer_pool_size=4G
    innodb_doublewrite=0
    innodb_file_per_table=1
    innodb_flush_method=O_DIRECT
    innodb_io_capacity=500
    innodb_log_file_size=1G
    innodb_old_blocks_time=1000
    innodb_read_io_threads=8
    innodb_write_io_threads=8

    wait_timeout=3600
    interactive_timeout=3600
    net_read_timeout=360
    net_write_timeout=360

    sync_binlog=1
    thread_cache_size=16
    table_open_cache=2048
    table_definition_cache=1024

  primaryConnection:
    secretName: mariadb-cluster-conn-primary
    secretTemplate:
      key: dsn
  primaryService:
    metadata:
      annotations:
        metallb.universe.tf/address-pool: primary
    type: LoadBalancer
  replicas: 3
  replication:
    enabled: true
  rootPasswordSecretKeyRef:
    generate: false
    key: root-password
    name: mariadb
  secondaryConnection:
    secretName: mariadb-cluster-conn-secondary
    secretTemplate:
      key: dsn
  secondaryService:
    metadata:
      annotations:
        metallb.universe.tf/address-pool: primary
    type: LoadBalancer
  service:
    metadata:
      annotations:
        metallb.universe.tf/address-pool: primary
    type: LoadBalancer
  storage:
    resizeInUseVolumes: true
    size: 10Gi
    storageClassName: general
    volumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: general
    waitForVolumeResize: true
  updateStrategy:
    type: RollingUpdate
  username: mariadb
