grafana:
  enabled: false
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
alertmanager:
  alertmanagerSpec:
    image:
      tag: ""
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: 15Gi
    nodeSelector:
      openstack-control-plane: enabled
    podAntiAffinity: ""
prometheusOperator:
  nodeSelector:
    openstack-control-plane: enabled
  admissionWebhooks:
    patch:
      nodeSelector:
        openstack-control-plane: enabled
  thanosImage:
    tag: ""

  kubeletService:
    enabled: true

kubelet:
  enabled: true
  serviceMonitor:
    enabled: true
    kubelet: true

kubeApiServer:
  enabled: false
  serviceMonitor:
    enabled: false

prometheus:
  prometheusSpec:
    image:
      tag: ""
    nodeSelector:
      openstack-control-plane: enabled
    podAntiAffinity: ""
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: 15Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
thanosRuler:
  thanosRulerSpec:
    image:
      tag: ""
    podAntiAffinity: ""

defaultRules:
  create: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
