---
sortOptions:
  order: fifo
resources:
  - ../base

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: manila-api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: manila-scheduler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: manila-data
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: manila-share
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
