---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: blazar
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "blazar"
    meta.helm.sh/release-namespace: "openstack"
spec:
  tags:
    - management
    - policymaker
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: openstack
  importCredentialsSecret:
    name: blazar-rabbitmq-password
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: blazar-vhost
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "blazar"
    meta.helm.sh/release-namespace: "openstack"
spec:
  name: "blazar"
  defaultQueueType: quorum
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: openstack
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: blazar-queue
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "blazar"
    meta.helm.sh/release-namespace: "openstack"
spec:
  name: blazar-qq
  vhost: "blazar"
  type: quorum
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: openstack
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: blazar-permission
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "blazar"
    meta.helm.sh/release-namespace: "openstack"
spec:
  vhost: "blazar"
  userReference:
    name: "blazar"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: openstack
