apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway-monitor
  namespace: prometheus
spec:
  endpoints:
    - interval: 15s
      port: metrics
  namespaceSelector:
    matchNames:
      - envoyproxy-gateway-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: envoyproxy-gateway
