galaxy_info:
  author: Punit Shankar Kundal
  description: Create the required pre-requisite resources for enabling amphora provider in Octavia
  company: Rackspace Technology
  license: Apache-2.0
  min_ansible_version: 2.15.8
  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
