apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: openstack
  annotations:
    metallb.universe.tf/address-pool: pool1
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_stomp
      - rabbitmq_stream
      - rabbitmq_web_mqtt
      - rabbitmq_web_stomp
  persistence:
    storageClassName: general
    storage: "20Gi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - worker
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - rabbitmq
        topologyKey: kubernetes.io/hostname
  override:
    service:
      spec:
        type: LoadBalancer
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "topology.kubernetes.io/zone"
              whenUnsatisfiable: ScheduleAnyway  # This should be changed to DoNotSchedule for production
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: openstack
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rabbitmq-disruption-budget
  namespace: openstack
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openstack
