grafana:
  enabled: false
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
alertmanager:
  alertmanagerSpec:
    image:
      tag: v0.26.0
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: 15Gi
    nodeSelector:
      openstack-control-plane: enabled
    podAntiAffinity: ""
prometheusOperator:
  nodeSelector:
    openstack-control-plane: enabled
  admissionWebhooks:
    patch:
      nodeSelector:
        openstack-control-plane: enabled
  thanosImage:
    tag: v0.34.0
  kubeletService:
    ## If true, the operator will create and maintain a service for scraping kubelets
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/helm/prometheus-operator/README.md
    ##
    enabled: true
kubelet:
  enabled: true
  serviceMonitor:
    enabled: true
    ## Enable scraping /metrics from kubelet's service
    kubelet: true
prometheus:
  prometheusSpec:
    image:
      tag: v2.49.1
    nodeSelector:
      openstack-control-plane: enabled
    podAntiAffinity: ""
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: 15Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
thanosRuler:
  thanosRulerSpec:
    image:
      tag: v0.34.0
    podAntiAffinity: ""

defaultRules:
  create: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
