---
# Copyright 2024-Present, Rackspace Technology, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: "Execute kubespray installer"
  block:
    - name: "Output"
      ansible.builtin.debug:
        msg:
          - "Executing kubespray installer in mode {{ kube_install_mode }}"
          - "Output will be send to /var/log/kubespray.log"
          - "Max timeout set to {{ async_timeout }} seconds"

    - name: "Execute kubespray cluster.yml"
      ansible.builtin.shell: |
        set -o pipefail #
        {% if pre_execution_hook is defined %}
        {{ pre_execution_hook }}
        {% endif %}
        ansible-playbook --forks {{ ansible_forks }} cluster.yml 2>&1 |tee -a /var/log/kubespray.log
        echo -e "\nRC: $?" |tee -a /var/log/kubespray.log
      args:
        executable: /bin/bash
        chdir: "{{ kubeprovider.path }}"
      register: _kubernetes_install
      changed_when:
        - "_kubernetes_install.rc == 0"
        - "_kubernetes_install.stdout |regex_search('changed=(1[0-9]*)')"
      failed_when: _kubernetes_install.rc not in [0]
      async: "{{ async_timeout }}"
      poll: 5
