---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-root
  namespace: openstack
spec:
  vhost: /
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-barbican
  namespace: openstack
spec:
  vhost: barbican
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-blazar
  namespace: openstack
spec:
  vhost: blazar
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-ceilometer
  namespace: openstack
spec:
  vhost: ceilometer
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-cinder
  namespace: openstack
spec:
  vhost: cinder
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-glance
  namespace: openstack
spec:
  vhost: glance
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-heat
  namespace: openstack
spec:
  vhost: heat
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-keystone
  namespace: openstack
spec:
  vhost: keystone
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-magnum
  namespace: openstack
spec:
  vhost: magnum
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-neutron
  namespace: openstack
spec:
  vhost: neutron
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-nova
  namespace: openstack
spec:
  vhost: nova
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-octavia
  namespace: openstack
spec:
  vhost: octavia
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-swift
  namespace: openstack
spec:
  vhost: swift
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-trove
  namespace: openstack
spec:
  vhost: trove
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-monitoring-permission-zaqar
  namespace: openstack
spec:
  vhost: zaqar
  user: monitoring
  permissions:
    configure: "^$"
    write: "^$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
