{
 "title": "Blackbox Exporter",
 "description": "A dashboard that monitors the Blackbox-exporter. It is created using the blackbox-exporter-mixin for the the (blackbox-exporter)[https://github.com/prometheus/blackbox-exporter].",
 "tags": [
  "blackbox-exporter",
  "blackbox-exporter-mixin"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(probe_success{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Map",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{\n  job=~\"$job\"\n}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Probes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  probe_success{\n    job=~\"$job\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Probes Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  count(\n    probe_success{\n      job=~\"$job\"\n    } == 1\n  )\n  OR vector(0)\n) /\ncount(\n  probe_success{\n    job=~\"$job\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Probes SSL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  probe_http_ssl{\n    job=~\"$job\"\n  } == 1\n) /\ncount(\n  probe_http_version{\n    job=~\"$job\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Probe Average Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  probe_duration_seconds{\n    job=~\"$job\"\n  }\n)\n"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "instance" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  probe_http_duration_seconds{\n    job=~\"$job\",\n    instance=~\"$instance\"\n  }\n) by (instance)\n",
     "legendFormat": "HTTP duration"
    },
    {
     "expr": "sum(\n  probe_duration_seconds{\n    job=~\"$job\",\n    instance=~\"$instance\"\n  }\n) by (instance)\n",
     "legendFormat": "Total probe duration"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n"
    }
   ]
  },
  {
   "title": "Latest Response Code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n"
    }
   ]
  },
  {
   "title": "SSL Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_tls_version_info{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "SSL Certificate Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{\n  job=~\"$job\",\n  instance=~\"$instance\"\n} - time()\n"
    }
   ]
  },
  {
   "title": "Probe Phases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  probe_http_duration_seconds{\n    job=~\"$job\",\n    instance=~\"$instance\"\n  }\n) by (phase)\n",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum(\n  probe_icmp_duration_seconds{\n    job=~\"$job\",\n    instance=~\"$instance\"\n  }\n) by (phase)\n",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Redirects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_redirects{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{\n  job=~\"$job\",\n  instance=~\"$instance\"\n}\n"
    }
   ]
  }
 ]
}