{
 "title": "Envoy Gateway Global",
 "description": "Envoy Gateway monitoring Dashboard with exported metrics.",
 "tags": [ "Control Plane" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(watchable_depth,namespace)"
    }
   },
   {
    "name": "Runner",
    "query": {
     "query": "label_values(watchable_depth,runner)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Watching Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration Bucket: $Runner",
   "type": "bargauge",
   "description": "How long in seconds a subscribed watchable is handled.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "repeat": "Runner",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (watchable_subscribe_duration_seconds_bucket{runner=~\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 1 },
   "repeat": "Runner",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(runner) (watchable_subscribe_duration_seconds_sum{runner=~\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max by(runner) (watchable_subscribe_duration_seconds_sum{runner=~\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Depth",
   "type": "stat",
   "description": "Current depth of watchable map.",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 1 },
   "repeat": "Runner",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(runner) (watchable_depth{runner=~\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 1 },
   "repeat": "Runner",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (watchable_subscribe_total{runner=\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(watchable_subscribe_total{runner=\"$Runner\", namespace=\"$Namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Status Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Recovered Panics",
   "type": "stat",
   "description": "Total number of panics recovered in the system.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(watchable_panics_recovered_total{namespace=\"$Namespace\"})",
     "legendFormat": "Recovered Panics"
    }
   ]
  },
  {
   "title": "Total Duration Bucket",
   "type": "bargauge",
   "description": "How long a status update takes to finish for all Kind.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (status_update_duration_seconds_bucket{namespace=\"$Namespace\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "status_update_duration_seconds_sum{namespace=\"$Namespace\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Max Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "status_update_duration_seconds_sum{namespace=\"$Namespace\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Min Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "expr": "status_update_duration_seconds_sum{namespace=\"$Namespace\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "description": "Total number of status updates by object kind.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kind) (status_update_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (status_update_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "xDS Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Snapshot Creation Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xds_snapshot_create_total{namespace=\"$Namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(status) (xds_snapshot_create_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Finished Stream",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(xds_stream_duration_seconds_bucket{namespace=\"$Namespace\", isDeltaStream=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Duration",
   "type": "stat",
   "description": "Maximum duration seconds for finished xDS delta stream connection.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "xds_stream_duration_seconds_sum{namespace=\"$Namespace\", isDeltaStream=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Duration",
   "type": "stat",
   "description": "Minimum duration seconds for finished xDS delta stream connection.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "xds_stream_duration_seconds_sum{namespace=\"$Namespace\", isDeltaStream=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Total",
   "type": "timeseries",
   "description": "Total number of xds snapshot cache updates by node id.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(nodeID) (xds_snapshot_update_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (xds_snapshot_update_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  { "title": "Infrastructure Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Total Apply Duration Bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (resource_apply_duration_seconds_bucket{namespace=\"$Namespace\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Apply Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (resource_apply_duration_seconds_sum{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Apply Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (resource_apply_duration_seconds_sum{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Apply Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (resource_apply_duration_seconds_sum{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Applied Resources",
   "type": "timeseries",
   "description": "Total number of applied resources sumed by kind.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by(kind) (resource_apply_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applied Resources Status",
   "type": "timeseries",
   "description": "Total number of applied resources that succeed sumed by kind.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
   "targets": [
    {
     "expr": "sum by(status) (resource_apply_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Applied Infrastructures",
   "type": "timeseries",
   "description": "Total number of applied resources sumed by infra name.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(name) (resource_apply_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delete Duration Bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (resource_delete_duration_seconds_bucket{namespace=\"$Namespace\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Delete Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (resource_delete_duration_seconds_sum{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Delete Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (resource_delete_duration_seconds_sum{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Delete Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "expr": "sum by(kind) (resource_delete_duration_seconds_sum{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Deleted Resources",
   "type": "timeseries",
   "description": "Total number of deleted resources sumed by kind.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum by(kind) (resource_delete_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Resources Status",
   "type": "timeseries",
   "description": "Total number of deleted resources that succeed sumed by kind.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
   "targets": [
    {
     "expr": "sum by(status) (resource_delete_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Deleted Infrastructures",
   "type": "timeseries",
   "description": "Total number of deleted resources sumed by infra name.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(name) (resource_delete_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wasm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Cache Entries",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wasm_cache_entries{namespace=\"$Namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Lookups",
   "type": "stat",
   "description": "Total number of Wasm remote fetch cache lookups.",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hit) (wasm_cache_lookup_total{namespace=\"$Namespace\"})",
     "legendFormat": "hit={{hit}}"
    }
   ]
  },
  {
   "title": "Cache Remote Fetches",
   "type": "stat",
   "description": "Total number of Wasm remote fetches and results.",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (wasm_remote_fetch_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(wasm_remote_fetch_total{namespace=\"$Namespace\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}