{
 "title": "OpenStack Exporter",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/openstack-exporter/openstack-exporter)",
 "tags": [
  "openstack",
  "openstack-exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_OPENSTACK_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Core Service Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nova agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(openstack_nova_agent_state{adminState=\"enabled\"}[1h]))-sum(last_over_time(openstack_nova_agent_state{adminState=\"enabled\"}[1h]))"
    }
   ]
  },
  {
   "title": "Nova agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_nova_agent_state{adminState=\"enabled\"}[1h])"
    }
   ]
  },
  {
   "title": "Nova agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_nova_agent_state{adminState=\"enabled\"}[1h]))"
    }
   ]
  },
  {
   "title": "Cinder agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\"}[1h]))-sum(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\"}[1h])))"
    }
   ]
  },
  {
   "title": "Cinder agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_cinder_agent_state[1h])"
    }
   ]
  },
  {
   "title": "Cinder agent up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\"}[1h]))"
    }
   ]
  },
  {
   "title": "Neutron agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(openstack_neutron_agent_state{adminState=\"up\"}[1h]))-sum(last_over_time(openstack_neutron_agent_state{adminState=\"up\"}[1h]))"
    }
   ]
  },
  {
   "title": "Neutron agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_neutron_agent_state[1h])"
    }
   ]
  },
  {
   "title": "Neutron agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_neutron_agent_state{adminState=\"up\"}[1h]))"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall CPU cores usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_vcpus_used)",
     "legendFormat": "used vcpu cores"
    },
    {
     "expr": "sum(openstack_nova_limits_vcpus_max)",
     "legendFormat": "available vcpu cores"
    }
   ]
  },
  {
   "title": "Overall memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_memory_used)",
     "legendFormat": "used memory"
    },
    {
     "expr": "sum(openstack_nova_limits_memory_max)",
     "legendFormat": "available memory"
    }
   ]
  },
  {
   "title": "Keystone projects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_identity_projects)"
    }
   ]
  },
  {
   "title": "Glance Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(openstack_glance_images)" }
   ]
  },
  {
   "title": "Nova instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(openstack_nova_total_vms)" }
   ]
  },
  {
   "title": "Associated, inactive FIPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips_associated_not_active)"
    }
   ]
  },
  {
   "title": "Neutron networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_networks)"
    }
   ]
  },
  {
   "title": "Neutron subnets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(openstack_neutron_subnets)" }
   ]
  },
  {
   "title": "Cinder volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(openstack_cinder_volumes)" }
   ]
  },
  {
   "title": "Cinder snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_cinder_snapshots)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Floating IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_floating_ips", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Networks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_networks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_ports", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Subnets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_subnets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Routers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_routers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Security Groups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_security_groups",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU core usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_nova_limits_vcpus_used/(openstack_nova_limits_vcpus_max+openstack_nova_limits_vcpus_used)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_nova_limits_memory_used/(openstack_nova_limits_memory_used+openstack_nova_limits_memory_max)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Local storage usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_local_storage_used_bytes/(openstack_nova_local_storage_used_bytes+openstack_nova_local_storage_available_bytes)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_nova_total_vms" }
   ]
  },
  {
   "title": "Availability Zones",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_availability_zones",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flavors",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "targets": [
    { "expr": "openstack_nova_flavor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vCPUs Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_vcpus_used)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vCPUs Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_limits_vcpus_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Local GB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_server_local_gb)",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume pool usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(openstack_cinder_pool_capacity_total_gb-openstack_cinder_pool_capacity_free_gb)/openstack_cinder_pool_capacity_total_gb",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume pool usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(openstack_cinder_volume_gb) by (volume_type)",
     "legendFormat": "{{volume_type}}"
    }
   ]
  },
  {
   "title": "Volumes Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_cinder_volumes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Volume Space Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_cinder_limits_volume_used_gb)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_glance_image_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Domains",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_identity_domains", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_identity_users", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Projects",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_identity_projects", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Groups",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_identity_groups", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Regions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_identity_regions", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Octavia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Loadbalancers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_loadbalancer_total_loadbalancers[1h]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loadbalancers In Error",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_loadbalancer_loadbalancer_status{provisioning_status=\"ERROR\"}) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Amphorae",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_loadbalancer_total_amphorae[1h]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Amphorae In Error",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_loadbalancer_amphora_status{status!~\"READY\"}) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Pools",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_loadbalancer_total_pools[1h]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pools In Error",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_loadbalancer_pool_status{provisioning_status=\"ERROR\"}) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}