---
apiVersion: v1
kind: Pod
metadata:
  name: "openstack-admin-client"
spec:
  restartPolicy: Always
  containers:
    - name: "openstack-admin-client"
      image: ghcr.io/rackerlabs/genestack-images/openstack-client:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "infinity"
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
      volumeMounts:
        - name: pod-tmp
          mountPath: /tmp
      env:
        - name: OS_IDENTITY_API_VERSION
          value: "3"
        - name: OS_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_AUTH_URL
        - name: OS_REGION_NAME
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_REGION_NAME
        - name: OS_INTERFACE
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_INTERFACE
        - name: OS_ENDPOINT_TYPE
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_INTERFACE
        - name: OS_PROJECT_DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_PROJECT_DOMAIN_NAME
        - name: OS_PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_PROJECT_NAME
        - name: OS_USER_DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_USER_DOMAIN_NAME
        - name: OS_USERNAME
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_USERNAME
        - name: OS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_PASSWORD
        - name: OS_DEFAULT_DOMAIN
          valueFrom:
            secretKeyRef:
              name: keystone-keystone-admin
              key: OS_DEFAULT_DOMAIN
        - name: OS_SERVICE_NAME
          value: "keystone"
        - name: OS_SERVICE_TYPE
          value: "image"
  volumes:
    - name: pod-tmp
      emptyDir: {}
