apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  containers:
    - name: kubectl
      image: alpine/k8s:1.33.13
      command:
        - sleep
        - "infinity"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
  restartPolicy: Always
