apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: magnum-conductor
  namespace: openstack
spec:
  maxReplicas: 9
  minReplicas: 3
  metrics:
    - resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 1Gi
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: magnum-conductor
