---
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: magnum-quorum-three-replicas
  namespace: openstack
spec:
  name: magnum-quorum-three-replicas
  vhost: "magnum"
  pattern: ".*"
  applyTo: queues
  definition:
    target-group-size: 3
  priority: 0
  rabbitmqClusterReference:
    name: rabbitmq
