sortOptions:
  order: fifo
resources:
  - qonos-rbac.yaml
  - qonos-mariadb-database.yaml
  - qonos-rabbitmq-queue.yaml
  - qonos-bin-configmap.yaml
  - qonos-ks-user-job.yaml
  - qonos-db-sync-job.yaml
  - api-deployment.yaml
  - scheduler-deployment.yaml
  - worker-deployment.yaml
  - qonos-servicemonitor.yaml
  - hpa-qonos-api.yaml
