import yaml
import os


def generate_matrix():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    input_file = os.path.join(repo_root, "helm-chart-versions.yaml")

    output_dir = os.path.join(repo_root, "docs")
    output_file = os.path.join(output_dir, "product-matrix.md")

    try:
        with open(input_file, "r") as f:
            data = yaml.safe_load(f)

        if "charts" not in data:
            print(f"Error: 'charts' key not found in {input_file}")
            return

        os.makedirs(output_dir, exist_ok=True)

        matrix_output = "Product Matrix with Helm Chart Versions\n\n"
        matrix_output += "This matrix is automatically generated by GitHub Actions.\n\n"
        matrix_output += "| Chart Name | Version |\n"
        matrix_output += "| :--- | :--- |\n"

        sorted_charts = sorted(data["charts"].items())

        for chart, version in sorted_charts:
            matrix_output += f"| **{chart}** | `{version}` |\n"

        with open(output_file, "w") as f:
            f.write(matrix_output)

        print(f"Successfully generated product matrix and saved to {output_file}")

    except FileNotFoundError:
        print(f"Error: Required file not found. Ensure '{input_file}' exists.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


if __name__ == "__main__":
    generate_matrix()
