---
# These are the tasks to create the certificate
# directories for client and server certificates
# as well other required files for openssl certs
- name: Create the base directory for octavia certs
  file:
    path: "{{ octavia_certs_dir }}"
    state: directory
    mode: '0700'

- name: Create the sub directories for certificates
  file:
    path: "{{ octavia_certs_dir }}/{{ item }}"
    state: directory
  loop:
    - certs
    - crl
    - csr
    - newcerts
    - private

- name: Set the permissions on private key directory
  file:
    path: "{{ octavia_certs_dir }}/private"
    state: directory
    mode: '0700'

- name: Create index file for the client and server certs
  file:
    path: "{{ octavia_certs_dir }}/index.txt"
    state: touch

- name: Create serial files for the client and server certs
  copy:
    content: '1000'
    dest: "{{ octavia_certs_dir }}/serial"

- name: Create openssl.cnf file required for the certificates
  template:
    src: "templates/openssl.cnf.j2"
    dest: "{{ octavia_certs_dir }}/openssl.cnf"
    mode: '0440'
