---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: nova
  namespace: openstack
spec:
  # If you want the database to be created with a different name than the resource name
  # name: data-custom
  mariaDbRef:
    name: mariadb-galera
  characterSet: utf8
  collate: utf8_general_ci
  retryInterval: 5s
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: nova-api
  namespace: openstack
spec:
  # If you want the database to be created with a different name than the resource name
  # name: data-custom
  name: nova_api
  mariaDbRef:
    name: mariadb-galera
  characterSet: utf8
  collate: utf8_general_ci
  retryInterval: 5s
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: nova-cell0
  namespace: openstack
spec:
  # If you want the database to be created with a different name than the resource name
  # name: data-custom
  name: nova_cell0
  mariaDbRef:
    name: mariadb-galera
  characterSet: utf8
  collate: utf8_general_ci
  retryInterval: 5s
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: nova
  namespace: openstack
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: nova-db-password
    key: password
  # This field is immutable and defaults to 10, 0 means unlimited.
  maxUserConnections: 0
  host: "%"
  retryInterval: 5s
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: nova-grant
  namespace: openstack
spec:
  mariaDbRef:
    name: mariadb-galera
  privileges:
    - "ALL"
  database: "nova"
  table: "*"
  username: nova
  grantOption: true
  host: "%"
  retryInterval: 5s
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: nova-api-grant
  namespace: openstack
spec:
  mariaDbRef:
    name: mariadb-galera
  privileges:
    - "ALL"
  database: "nova_api"
  table: "*"
  username: nova
  grantOption: true
  host: "%"
  retryInterval: 5s
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: nova-cell0-grant
  namespace: openstack
spec:
  mariaDbRef:
    name: mariadb-galera
  privileges:
    - "ALL"
  database: "nova_cell0"
  table: "*"
  username: nova
  grantOption: true
  host: "%"
  retryInterval: 5s
