apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: designate-api
  namespace: openstack
spec:
  maxReplicas: 9
  minReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 500Mi
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: designate-api
