---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: heat
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "heat"
    meta.helm.sh/release-namespace: "openstack"
spec:
  # If you want the database to be created with a different name than the resource name
  # name: data-custom
  mariaDbRef:
    name: mariadb-cluster
  characterSet: utf8
  collate: utf8_general_ci
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: heat
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "heat"
    meta.helm.sh/release-namespace: "openstack"
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: mariadb-cluster
  passwordSecretKeyRef:
    name: heat-db-password
    key: password
  # This field is immutable and defaults to 10, 0 means unlimited.
  maxUserConnections: 0
  host: "%"
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: heat-grant
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: "heat"
    meta.helm.sh/release-namespace: "openstack"
spec:
  mariaDbRef:
    name: mariadb-cluster
  privileges:
    - "ALL"
  database: "heat"
  table: "*"
  username: heat
  grantOption: true
  host: "%"
  retryInterval: 5s
