apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: heat-engine
  namespace: openstack
spec:
  maxReplicas: 9
  minReplicas: 3
  metrics:
    - resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 500Mi
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: heat-engine
