---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: heat-engine
  namespace: openstack
spec:
  maxReplicas: 9
  minReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: heat-engine
