sortOptions:
  order: fifo
resources:
  - heat-mariadb-database.yaml
  - heat-rabbitmq-queue.yaml
  - all.yaml
  - hpa-heat-api.yaml
  - hpa-heat-cfn.yaml
  - hpa-heat-engine.yaml
  - heat-routes.yaml
