---
- name: Obtain the ip addresses of the ports for the capi mgmt cluster
  openstack.cloud.port_info:
    interface: "{{ os_endpoint_type | default('public') }}"
    name: "{{ item.name }}"
  register: _capi_ports
  loop: "{{ capi_mgmt_cluster_ports }}"

- name: Create the list of ip addresses for the ports
  ansible.builtin.set_fact:
    _capi_cluster_port_ips: "{{ _capi_cluster_port_ips | default([]) + [ item.ports[0].fixed_ips[0].ip_address ] }}"
  loop: "{{ _capi_ports.results }}"

- name: Create the loadbalancer for the capi mgmt cluster
  openstack.cloud.loadbalancer:
    interface: "{{ os_endpoint_type | default('public') }}"
    state: present
    name: "{{ capi_mgmt_cluster_lb_name }}"
    vip_network: "{{ ext_net_id }}"
  register: _capi_lb

- name: Create the listener for the capi mgmt cluster lb
  openstack.cloud.lb_listener:
    interface: "{{ os_endpoint_type | default('public') }}"
    state: present
    name: "{{ capi_mgmt_cluster_lb_listener_name }}"
    load_balancer: "{{ _capi_lb.load_balancer.id }}"
    protocol: TCP
    protocol_port: 6443
  register: _capi_lb_listener

- name: Create the pool for the capi mgmt cluster lb
  openstack.cloud.lb_pool:
    interface: "{{ os_endpoint_type | default('public') }}"
    state: present
    name: "{{ capi_mgmt_cluster_lb_pool_name }}"
    listener: "{{ _capi_lb_listener.listener.id }}"
    lb_algorithm: ROUND_ROBIN
    protocol: TCP
  register: _capi_lb_pool

- name: Create the members for the capi mgmt cluster lb
  openstack.cloud.lb_member:
    interface: "{{ os_endpoint_type | default('public') }}"
    state: present
    name: "member-{{ item }}"
    pool: "{{ _capi_lb_pool.pool.id }}"
    address: "{{ item }}"
    protocol_port: 6443
    subnet_id: "{{ _capi_geneve_subnet.id }}"
  loop: "{{ _capi_cluster_port_ips }}"
