name: Helm GitHub Actions for Libvirt

on:
  pull_request:
    paths:
      - base-helm-configs/libvirt/**
      - .github/workflows/helm-libvirt.yaml
jobs:
  helm:
    strategy:
      matrix:
        overlays:
          - base
    name: Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: "${{ secrets.GITHUB_TOKEN }}"
        id: helm
      - name: Kubectl Install
        working-directory: /usr/local/bin/
        run: |
            if [ ! -f /usr/local/bin/kubectl ]; then
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x ./kubectl
            fi
      - name: Pull OSH submodules
        run: |
            git submodule update --init submodules/openstack-helm
            git submodule update --init submodules/openstack-helm-infra
      - name: Make OSH submodule
        run: |
            cd submodules/openstack-helm-infra
            make libvirt
      - name: Run Helm Template
        run: |
          cd submodules/openstack-helm-infra
          ${{ steps.helm.outputs.helm-path }} template libvirt ./libvirt \
            --namespace=openstack \
            --wait \
            --timeout 120m \
            -f ${{ github.workspace }}/base-helm-configs/libvirt/libvirt-helm-overrides.yaml  > /tmp/rendered.yaml
      - name: Return helm Build
        uses: actions/upload-artifact@v4
        with:
          name: helm-libvirt-artifact-${{ matrix.overlays }}
          path: /tmp/rendered.yaml
