---
name: Helm GitHub Actions for Blazar Reservation Splitter

on:
  pull_request:
    paths:
      - base-helm-configs/blazar-reservation-splitter/**
      - base-kustomize/blazar-reservation-splitter/**
      - .github/workflows/helm-blazar-reservation-splitter.yaml
jobs:
  helm:
    strategy:
      matrix:
        overlays:
          - base
    name: Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: v3.14.3
          token: ${{ secrets.GITHUB_TOKEN }}
        id: helm
      - name: Kubectl Install
        working-directory: /usr/local/bin/
        run: |
          if [ ! -f /usr/local/bin/kubectl ]; then
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
          fi
      - name: Add blazar-reservation-splitter repo to helm
        run: |
          helm repo add genestack-blazar-reservation-splitter-helm-chart https://rackerlabs.github.io/genestack-blazar-reservation-splitter-helm-chart
          helm repo update
      - name: Run Helm Template
        run: |
          ${{ steps.helm.outputs.helm-path }} template blazar-reservation-splitter genestack-blazar-reservation-splitter-helm-chart/blazar-reservation-splitter \
            --namespace=openstack \
            --wait \
            --timeout 120m \
            -f ${{ github.workspace }}/base-helm-configs/blazar-reservation-splitter/blazar-reservation-splitter-helm-overrides.yaml
            --post-renderer ${{ github.workspace }}/base-kustomize/kustomize.sh \
            --post-renderer-args blazar/${{ matrix.overlays }} > /tmp/rendered.yaml
      - name: Return helm Build
        uses: actions/upload-artifact@v4
        with:
          name: helm-blazar-reservation-splitter-artifact-${{ matrix.overlays }}
          path: /tmp/rendered.yaml
