name: Kustomize GitHub Actions for rook-operator

on:
  pull_request:
    paths:
      - base-kustomize/rook-operator/**
      - .github/workflows/kustomize-rook-operator.yaml
jobs:
  kustomize:
    name: Kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Kustomize Install
        working-directory: /usr/local/bin/
        run: |
          if [ ! -f /usr/local/bin/kustomize ]; then
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
          fi
      - name: Run Kustomize Build
        run: |
          kustomize build base-kustomize/rook-operator/base > /tmp/rendered.yaml
      - name: Return Kustomize Build
        uses: actions/upload-artifact@v4
        with:
          name: kustomize-rook-operator-artifact
          path: /tmp/rendered.yaml
