name: Kustomize GitHub Actions for Gateway API(envoyproxy)

on:
  pull_request:
    paths:
      - base-kustomize/gateway/envoyproxy-gateway/**
      - .github/workflows/kustomize-gateway-api-envoyproxy.yaml
jobs:
  kustomize:
    name: Kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: "${{ secrets.GITHUB_TOKEN }}"
        id: helm
      - name: Kustomize Install
        working-directory: /usr/local/bin/
        run: |
          if [ ! -f /usr/local/bin/kustomize ]; then
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
          fi
      - name: Run Kustomize Build
        run: |
          kustomize build base-kustomize/envoyproxy-gateway/base > /tmp/rendered.yaml
      - name: Return Kustomize Build
        uses: actions/upload-artifact@v4
        with:
          name: kustomize-gateway-artifact
          path: /tmp/rendered.yaml
