name: Run pull-request syntax workflows
on:
  - pull_request
jobs:
  pre_commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1
      - name: Run Check
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: >-
            --files ${{ steps.changed-files.outputs.all_changed_files }}
            --hook-stage manual
      - name: Checks failed, notification
        if: failure()
        run: |
          echo "Tests Failed"
          echo "Run the following command to identify issues"
          echo "pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}"
      - name: Upload log artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pre-commit-py${{ matrix.python-version }}
          path: /home/runner/.cache/pre-commit/pre-commit.log
