name: Run pull-request syntax workflows
on:
  - pull_request

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Fetch all branches and tags
        run: git fetch --prune --unshallow
      - name: Determine changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ | xargs)
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
      - name: Run Check
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: >-
            --files ${{ env.CHANGED_FILES }}
            --hook-stage manual
